### ISSUE TITLE
Lograr que se impriman las alumnas 

### ISSUE THREAD

**Issue by elment9** [elment9/lim-2018-05-bc-core-pm-datadashboard#12]
Hacer que se impriman las alumnas cuando se haga clic en una determinada opcion del select .

**Comment by jslyne** [comment]
Listo. Las alumnas se muestran en la pestaña .. su nombre y su id

**Comment by elment9** [comment]
Se volverá a replantear esto

**Comment by elment9** [comment]
@jslyne hay que replantear esto.
